# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: back-config
# data:
#   PORT: "5000"
#   PAYPAL_API_URL: "https://api-m.sandbox.paypal.com"
#   SEED_ON_START: "true"
#   NODE_ENV: production
