apiVersion: v1
kind: Secret
metadata:
  name: proshop-secret
type: Opaque
data:
  JWT_SECRET: "Y2hhbmdlbWVfc3VwZXJfc2VjcmV0X2Zvcl9kZXY="
  MONGO_URI: "bW9uZ29kYjovL2FkbWluOnJvb3RAZGItc3ZjOjI3MDE3L3Byb3Nob3A/YXV0aFNvdXJjZT1hZG1pbg=="
  PAYPAL_CLIENT_ID: "c2I="
  PAYPAL_APP_SECRET: "c2Jfc2VjcmV0"
