apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque 
stringData: 
  MONGO_INITDB_ROOT_USERNAME: admin
  MONGO_INITDB_ROOT_PASSWORD: root
  MONGO_INITDB_DATABASE: proshop
  ADMIN_PASSWORD_HASH: "$2a$10$E7VjWIKdiQgkXxmOquowS.GQ4rfNl/RWfw1G4xQ8sSW.sfIRJg8La"
