apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  labels:
    {{- include "proshop.labels" . | nindent 4 }}
type: Opaque
stringData:
  JWT_SECRET: {{ .Values.app.secrets.jwtSecret }}
  MONGO_URI: {{ include "proshop.mongodb.uri" . | b64enc | b64dec }}
  PAYPAL_CLIENT_ID: {{ .Values.app.secrets.paypalClientId }}
  PAYPAL_APP_SECRET: {{ .Values.app.secrets.paypalAppSecret }}
