{{- if .Values.mongodb.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mongo-secret
  labels:
    {{- include "proshop.labels" . | nindent 4 }}
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: {{ .Values.mongodb.auth.rootUsername }}
  MONGO_INITDB_ROOT_PASSWORD: {{ .Values.mongodb.auth.rootPassword }}
  MONGO_INITDB_DATABASE: {{ .Values.mongodb.auth.database }}
{{- end }}
