apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-svc
  labels:
    {{- include "proshop.labels" . | nindent 4 }}
spec:
  type: {{ .Values.app.service.type }}
  selector:
    {{- include "proshop.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.app.service.port }}
      targetPort: {{ .Values.app.service.targetPort }}
      {{- if and (eq .Values.app.service.type "NodePort") .Values.app.service.nodePort }}
      nodePort: {{ .Values.app.service.nodePort }}
      {{- end }}
      name: http