apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: db-secrets-mapping
  namespace: pro-shop
spec:
  refreshInterval: 15m
  secretStoreRef:
    name: aws-secrets
    kind: ClusterSecretStore
  target:
    name: mongo-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: /prod/mongo/credentials
