app:
  name: proshop
  replicaCount: 1
  
  image:
    repository: abdullahhamada7/proshop
    pullPolicy: IfNotPresent
    tag: "latest"
  
  service:
    type: NodePort
    port: 5000
    targetPort: 5000
    nodePort: 30100
  
  resources:
    requests:
      cpu: "350m"      
      memory: "200Mi"  
    limits:
      cpu: "700m"      
      memory: "400Mi"  
  
  config:
    port: "5000"
    nodeEnv: production
    seedOnStart: "true"
    paypalApiUrl: "https://api-m.sandbox.paypal.com"
  
  secrets:
    jwtSecret: "changeme_super_secret_for_dev"
    paypalClientId: "sb"
    paypalAppSecret: "sb_secret"

mongodb:
  enabled: true
  name: mongo
  replicaCount: 1
  
  image:
    repository: mongo
    tag: "6.0"
    pullPolicy: IfNotPresent
  
  service:
    port: 27017
    targetPort: 27017
  
  auth:
    rootUsername: admin
    rootPassword: root
    database: proshop
  
  persistence:
    enabled: true
    storageClass: ""
    accessMode: ReadWriteOnce
    size: 1Gi
  
  initDb:
    enabled: true