apiVersion: v1
kind: Service
metadata:
  name: db-svc
  labels:
    app: mongo
    env: production
    version: v1.0
    tier: database
  annotations:
    maintainer: "Team 274"  
    description: "Service for ProShop MongoDB database"
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: mongo
  clusterIP: None # headless service for stateful set
