apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
  labels:
    app: mongo
    env: production
    version: v1.0
    tier: database
  annotations:
    maintainer: "Team 274"
    description: "StatefulSet for ProShop MongoDB database"
spec:
  serviceName: db-svc
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: mongo:6.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 27017
              name: mongo
          envFrom:
            - secretRef:
                name: mongo-secret
          volumeMounts: # Mount volumes for data and initialization script
            - name: mongo-data
              mountPath: /data/db
            - name: mongo-init-script
              mountPath: /docker-entrypoint-initdb.d/init.js
              subPath: init.js
              readOnly: true
      volumes: # Volume for initialization script
        - name: mongo-init-script
          configMap:
            name: mongo-init-script
  volumeClaimTemplates: # Define persistent volume claim for MongoDB data
    - metadata:
        name: mongo-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
